# Generated by Django 2.0.5 on 2020-04-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('state', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Done')])),
            ],
        ),
    ]
